name: comtrade_fe
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  archive: ^3.6.1
  dio: ^5.7.0
  excel: ^4.0.6
  file_picker: ^8.0.5
  syncfusion_flutter_charts: ^28.2.6
  fl_chart: ^0.70.2
  flutter:
    sdk: flutter
  http: ^1.2.2
  path_provider: ^2.1.4
  provider: ^6.0.3
  universal_platform: ^1.1.0
  collection: ^1.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
